- client-bagel-buddy/public/manifest.json
- client-bagel-buddy/src/components/button/index.css
- client-bagel-buddy/src/components/button/index.js
- client-bagel-buddy/src/containers/student/lesson/index.js
- client-bagel-buddy/src/containers/student/lesson/upcoming/upcoming.js
- client-bagel-buddy/src/index.css
> 30 create button component

- client-bagel-buddy/src/containers/student/lesson/index.css
- client-bagel-buddy/src/containers/student/lesson/index.js
- client-bagel-buddy/src/containers/student/lesson/upcoming/upcoming.js
- client-bagel-buddy/src/index.css
> feat: add upcoming

- client-bagel-buddy/src/components/card/index.css
- client-bagel-buddy/src/components/card/index.js
- client-bagel-buddy/src/containers/student/home/home.css
- client-bagel-buddy/src/containers/student/home/home.js
- client-bagel-buddy/src/containers/student/teacherList/teacherDetail.js
- client-bagel-buddy/src/index.css
> feat: add card to homepage

- client-bagel-buddy/src/index.css
https://fonts.google.com/specimen/Inter?query=Inter
> fix: change to Inter

- client-bagel-buddy/src/containers/student/teacherList/teacherDetail.css
- client-bagel-buddy/src/containers/student/teacherList/teacherDetail.js
> feat: add review section

- README.md
- client-bagel-buddy/src/App.js
- client-bagel-buddy/src/App.test.js
- client-bagel-buddy/src/components/Header.css
- client-bagel-buddy/src/components/Header.js
- client-bagel-buddy/src/components/card/index.css
- client-bagel-buddy/src/components/card/index.js
- client-bagel-buddy/src/containers/onboard/index.css
- client-bagel-buddy/src/containers/onboard/index.js
- client-bagel-buddy/src/containers/onboard/index.test.js
- client-bagel-buddy/src/index.css
> 51 login flow

- client-bagel-buddy/src/components/button/index.css
- client-bagel-buddy/src/components/card/index.css
- client-bagel-buddy/src/components/card/index.js
> fix: chip on main

- client-bagel-buddy/src/containers/student/teacherList/teacherDetail.css
- client-bagel-buddy/src/containers/student/teacherList/teacherDetail.js
Finished task 18, ready to compare and merge.
> Task 18 finished, submitting

- client-bagel-buddy/src/containers/student/lesson/pending/pending.js
- client-bagel-buddy/src/containers/student/teacherList/teacherDetail.css
- client-bagel-buddy/src/containers/student/teacherList/teacherDetail.js
Finished task 20 if someone wants to look over it and see if it does the job.
> Hazel finished task 20

- client-bagel-buddy/src/App.js
- client-bagel-buddy/src/components/popup/index.css
- client-bagel-buddy/src/components/popup/index.js
- client-bagel-buddy/src/containers/student/lesson/canceled/canceled.js
- client-bagel-buddy/src/containers/student/lesson/pending/pending.js
- client-bagel-buddy/src/index.css
Hazel finished issue 27. Created a popup component to be used throughout the platform. Created a pending page for students.
> 27 student lesson pending

- client-bagel-buddy/src/components/popup/index.css
- client-bagel-buddy/src/components/popup/index.js
- client-bagel-buddy/src/containers/student/lesson/canceled/canceled.js
> feat: add edit mode in popup

- client-bagel-buddy/src/containers/teacher/lesson/canceled/canceled.js
Added teacher cancellation page, just a replica of the student's for now.
> added teacher cancel page

- client-bagel-buddy/src/containers/teacher/lesson/history/history.js
Teachers can see a review left for them
> added history message for teachers

- client-bagel-buddy/src/containers/student/teacherList/teacherDetail.css
- client-bagel-buddy/src/containers/student/teacherList/teacherDetail.js
> fixed weird layout issue

- client-bagel-buddy/src/components/popup/index.css
- client-bagel-buddy/src/components/popup/index.js
- client-bagel-buddy/src/containers/student/lesson/history/history.js
> feat: add star in rating popup

- client-bagel-buddy/src/components/header/Header.css
- client-bagel-buddy/src/components/header/Header.js
> feat: add profile popup

- client-bagel-buddy/src/containers/onboard/index.css
- client-bagel-buddy/src/containers/onboard/index.js
> fix: change p to label for a11y

- client-bagel-buddy/src/api/lesson.js
- client-bagel-buddy/src/containers/teacher/lesson/canceled/canceled.js
This issue should be complete.
> Hazel pushing work that Wendee and I did

- client-bagel-buddy/src/components/header/Header.js
- client-bagel-buddy/src/containers/student/lesson/canceled/canceled.js
Students can view cancellation messages on the cancelled lessons page.
> Feat: added cancellation messages on the student side as well.

- client-bagel-buddy/src/containers/student/home/home.js
Student header now displays the user's name and number of points.
> feat: added personalization to student header

- client-bagel-buddy/src/api/user.js
- client-bagel-buddy/src/components/header/Header.css
- client-bagel-buddy/src/components/header/Header.js
Getting stuck with allowing the user to edit their bio in their profile.
> feat: trying to allow users to edit introduction in profile
